### ISSUE TITLE
install_nodejs.sh 스크립트 

### ISSUE THREAD

**Issue by SeongJuMoon** [posquit0/packer-templates#1]
아래에 해당하는 install 스크립트에 오타가 있어 제보드립니다.
https://github.com/posquit0/packer-templates/blob/6439239686cb05f01db3340d3f33d8977000bbaa/scripts/install-nodejs.sh#L19

**Comment by posquit0** [comment]
감사합니다. 혹시나 PR로 올려주시면 머지할게요! :)
